# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       gstreamer1-plugins-good

# >> macros
# << macros
%define majorminor 1.0

Summary:    GStreamer plugins with good code and licensing
Version:    1.4.1
Release:    1
Group:      Applications/Multimedia
License:    LGPLv2+
URL:        http://gstreamer.freedesktop.org/
Source0:    %{name}-%{version}.tar.xz
Source100:  gstreamer1-plugins-good.yaml
BuildRequires:  pkgconfig(gstreamer-1.0)
BuildRequires:  pkgconfig(gstreamer-plugins-base-1.0)
BuildRequires:  pkgconfig(orc-0.4) >= 0.4.18
BuildRequires:  pkgconfig(python)
BuildRequires:  pkgconfig(speex)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(libsoup-2.4)
BuildRequires:  pkgconfig(pango)
BuildRequires:  pkgconfig(alsa)
BuildRequires:  pkgconfig(libpulse)
BuildRequires:  pkgconfig(taglib)
BuildRequires:  pkgconfig(flac)
BuildRequires:  pkgconfig(gudev-1.0)
BuildRequires:  bison
BuildRequires:  flex
BuildRequires:  libjpeg-devel
BuildRequires:  gettext-devel
BuildRequires:  intltool

%description
GStreamer is a streaming media framework, based on graphs of filters which
operate on media data. Applications using this library can do anything
from real-time sound processing to playing videos, and just about anything
else media-related.  Its plugin-based architecture means that new data
types or processing capabilities can be added simply by installing new
plug-ins.

GStreamer Good Plugins is a collection of well-supported plugins of
good quality and under the LGPL license.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
export CFLAGS="-DG_DISABLE_ASSERT -DG_DISABLE_CAST_CHECKS"
export NOCONFIGURE="1"
%autogen
# << build pre

%configure --disable-static \
    --with-package-name='Maui GStreamer package' \
    --with-package-origin='http://www.maui-project.org/' \
    --with-default-visualizer=autoaudiosink \
    --enable-experimental \
    --enable-gtk-doc=no \
    --enable-introspection=no \
    --enable-orc \
    --disable-monoscope \
    --disable-aalib \
    --disable-cairo \
    --disable-libcaca \
    --disable-jack \
    --disable-examples \
    --disable-freetypetest

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
%find_lang gst-plugins-good-%{majorminor}

# Remove files we don't want
find $RPM_BUILD_ROOT -name '*.la' -exec rm -f {} ';'
# << install post

%files -f gst-plugins-good-%{majorminor}.lang
%defattr(-,root,root,-)
# >> files
%doc AUTHORS COPYING README REQUIREMENTS
%dir %{_datadir}/gstreamer-%{majorminor}/presets/
%{_datadir}/gstreamer-%{majorminor}/presets/GstIirEqualizer10Bands.prs
%{_datadir}/gstreamer-%{majorminor}/presets/GstIirEqualizer3Bands.prs
%{_libdir}/gstreamer-%{majorminor}/libgst*.so
# << files
